//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelpDeskEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class AutoAssign
    {
        public int Id { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public Nullable<int> OperatorId { get; set; }
        public Nullable<int> SupportTeamId { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string ModifiedBy { get; set; }
    
        public virtual SupportTeam SupportTeam { get; set; }
        public virtual User User { get; set; }
        public virtual SupportCategory SupportCategory { get; set; }
        public virtual Company Company { get; set; }
    }
}
