//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelpDeskEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        public Company()
        {
            this.AutoAssigns = new HashSet<AutoAssign>();
            this.Companies1 = new HashSet<Company>();
            this.Tickets = new HashSet<Ticket>();
            this.Users = new HashSet<User>();
        }
    
        public int CompanyId { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public Nullable<int> ParentId { get; set; }
        public string CompanyName { get; set; }
        public string Address { get; set; }
        public bool IsEnable { get; set; }
        public bool ShareParentContract { get; set; }
        public Nullable<int> CAP { get; set; }
        public string City { get; set; }
        public string Contact { get; set; }
        public string VAT { get; set; }
        public string Mail { get; set; }
        public string PEC { get; set; }
        public string BadgeFormat { get; set; }
        public string AccessId { get; set; }
        public Nullable<int> UseSalePriceNr { get; set; }
        public string Note { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime ModifiedOn { get; set; }
        public string ModifiedBy { get; set; }
    
        public virtual ICollection<AutoAssign> AutoAssigns { get; set; }
        public virtual ICollection<Company> Companies1 { get; set; }
        public virtual Company Company1 { get; set; }
        public virtual ICollection<Ticket> Tickets { get; set; }
        public virtual ICollection<User> Users { get; set; }
    }
}
