//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelpDeskEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyProduct
    {
        public int CompanyId { get; set; }
        public int SupplierId { get; set; }
        public int SupplierProductId { get; set; }
        public string SerialNumber { get; set; }
        public string PartNumber { get; set; }
        public string Location { get; set; }
        public string FirmwareVersion { get; set; }
        public Nullable<System.DateTime> PurchaseDate { get; set; }
        public string IPAddress { get; set; }
        public string Power { get; set; }
        public string Note { get; set; }
        public string Equipment { get; set; }
        public string Credentials { get; set; }
        public Nullable<decimal> SalePrice { get; set; }
        public Nullable<decimal> PurchasePrice { get; set; }
        public Nullable<short> GuaranteeMonths { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime ModifiedOn { get; set; }
        public string ModifiedBy { get; set; }
    }
}
