//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelpDeskEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompCatException
    {
        public int CompanyCategoryExceptionId { get; set; }
        public int CompanyId { get; set; }
        public int CategoryId { get; set; }
    
        public virtual Company Company { get; set; }
    }
}
