//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelpDeskEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CuteChat4_SupportDepartment
    {
        public CuteChat4_SupportDepartment()
        {
            this.CuteChat4_SupportAgent = new HashSet<CuteChat4_SupportAgent>();
        }
    
        public int DepartmentId { get; set; }
        public string DepartmentName { get; set; }
    
        public virtual ICollection<CuteChat4_SupportAgent> CuteChat4_SupportAgent { get; set; }
    }
}
