//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelpDeskEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CuteChat4_Lobby
    {
        public int LobbyId { get; set; }
        public string Title { get; set; }
        public string Topic { get; set; }
        public string Announcement { get; set; }
        public bool Locked { get; set; }
        public bool AllowAnonymous { get; set; }
        public string Password { get; set; }
        public string Description { get; set; }
        public string Integration { get; set; }
        public string ManagerList { get; set; }
        public int MaxOnlineCount { get; set; }
        public int MaxIdleMinute { get; set; }
        public int AutoAwayMinute { get; set; }
        public int HistoryCount { get; set; }
        public int HistoryDay { get; set; }
        public int SortIndex { get; set; }
    }
}
