//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelpDeskEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CuteChat4_Rule
    {
        public int RuleId { get; set; }
        public string Category { get; set; }
        public int SortIndex { get; set; }
        public string RuleMode { get; set; }
        public string Expression { get; set; }
        public bool Disabled { get; set; }
    }
}
