//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelpDeskEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CuteChat4_LogEvent
    {
        public int EventId { get; set; }
        public System.DateTime EvtTime { get; set; }
        public string Category { get; set; }
        public string Message { get; set; }
        public string Portal { get; set; }
        public string Place { get; set; }
        public string UserName { get; set; }
        public string UserId { get; set; }
    }
}
