//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelpDeskEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CuteChat4_SupportSession
    {
        public int SessionId { get; set; }
        public System.DateTime BeginTime { get; set; }
        public int DepartmentId { get; set; }
        public string AgentUserId { get; set; }
        public string CustomerId { get; set; }
        public string DisplayName { get; set; }
        public System.DateTime ActiveTime { get; set; }
        public string Email { get; set; }
        public string IPAddress { get; set; }
        public string Culture { get; set; }
        public string Platform { get; set; }
        public string Browser { get; set; }
        public int AgentRating { get; set; }
        public string SessionData { get; set; }
        public string Url { get; set; }
        public string Referrer { get; set; }
    }
}
