//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelpDeskEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CuteChat4_User
    {
        public string UserId { get; set; }
        public string DisplayName { get; set; }
        public string Description { get; set; }
        public string BuildinIgnores { get; set; }
        public string BuildinContacts { get; set; }
        public string ServerProperties { get; set; }
        public string PublicProperties { get; set; }
        public string PrivateProperties { get; set; }
    }
}
