//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelpDeskEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CuteChat4_SupportFeedback
    {
        public int FeedbackId { get; set; }
        public System.DateTime FbTime { get; set; }
        public string CustomerId { get; set; }
        public string DisplayName { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Title { get; set; }
        public string Content { get; set; }
        public string Comment { get; set; }
        public string CommentBy { get; set; }
    }
}
