//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelpDeskEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CuteChat4_LogMessage
    {
        public int MessageId { get; set; }
        public System.DateTime MsgTime { get; set; }
        public string Location { get; set; }
        public string Place { get; set; }
        public string Sender { get; set; }
        public string SenderId { get; set; }
        public string Target { get; set; }
        public string TargetId { get; set; }
        public int Whisper { get; set; }
        public string IPAddress { get; set; }
        public string Text { get; set; }
        public string Html { get; set; }
    }
}
