//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelpDeskEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailInbox
    {
        public int Id { get; set; }
        public Nullable<bool> Processed { get; set; }
        public Nullable<int> UserId { get; set; }
        public string MessageId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string FromAddress { get; set; }
        public string Subject { get; set; }
        public string Body { get; set; }
        public Nullable<short> Attachments { get; set; }
        public string FileName { get; set; }
        public string LinkedToTicketId { get; set; }
    }
}
