

//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;


public partial class Attachment
{

    public int AttachmentId { get; set; }

    public int LinkId { get; set; }

    public int LinkType { get; set; }

    public string FileName { get; set; }

    public string FilePath { get; set; }

    public Nullable<System.DateTime> CreatedOn { get; set; }

    public string CreatedBy { get; set; }

    public Nullable<System.DateTime> ModifiedOn { get; set; }

    public string ModifiedBy { get; set; }

}


public partial class AutoAssign
{

    public int Id { get; set; }

    public Nullable<int> CompanyId { get; set; }

    public Nullable<int> CategoryId { get; set; }

    public Nullable<int> OperatorId { get; set; }

    public Nullable<int> SupportTeamId { get; set; }

    public Nullable<System.DateTime> CreatedOn { get; set; }

    public string CreatedBy { get; set; }

    public Nullable<System.DateTime> ModifiedOn { get; set; }

    public string ModifiedBy { get; set; }



    public virtual SupportTeam SupportTeam { get; set; }

    public virtual User User { get; set; }

    public virtual SupportCategory SupportCategory { get; set; }

    public virtual Company Company { get; set; }

}


public partial class Comment
{

    public int CommentId { get; set; }

    public System.Guid TicketId { get; set; }

    public bool IsPrivate { get; set; }

    public string CommentText { get; set; }

    public Nullable<int> CreatedOpt_Id { get; set; }

    public Nullable<int> CreatedUser_Id { get; set; }

    public System.DateTime CreatedOn { get; set; }



    public virtual Comment Comments1 { get; set; }

    public virtual Comment Comment1 { get; set; }

}


public partial class Company
{

    public Company()
    {

        this.AutoAssigns = new HashSet<AutoAssign>();

        this.Companies1 = new HashSet<Company>();

        this.Tickets = new HashSet<Ticket>();

        this.Users = new HashSet<User>();

    }


    public int CompanyId { get; set; }

    public Nullable<int> CategoryId { get; set; }

    public Nullable<int> ParentId { get; set; }

    public string CompanyName { get; set; }

    public string Address { get; set; }

    public bool IsEnable { get; set; }

    public bool ShareParentContract { get; set; }

    public Nullable<int> CAP { get; set; }

    public string City { get; set; }

    public string Contact { get; set; }

    public string VAT { get; set; }

    public string Mail { get; set; }

    public string PEC { get; set; }

    public string BadgeFormat { get; set; }

    public string AccessId { get; set; }

    public Nullable<int> UseSalePriceNr { get; set; }

    public string Note { get; set; }

    public System.DateTime CreatedOn { get; set; }

    public string CreatedBy { get; set; }

    public System.DateTime ModifiedOn { get; set; }

    public string ModifiedBy { get; set; }



    public virtual ICollection<AutoAssign> AutoAssigns { get; set; }

    public virtual ICollection<Company> Companies1 { get; set; }

    public virtual Company Company1 { get; set; }

    public virtual ICollection<Ticket> Tickets { get; set; }

    public virtual ICollection<User> Users { get; set; }

}


public partial class CompanyCategory
{

    public int Id { get; set; }

    public string Name { get; set; }

    public System.DateTime CreatedOn { get; set; }

    public string CreatedBy { get; set; }

    public System.DateTime ModifiedOn { get; set; }

    public string ModifiedBy { get; set; }

}


public partial class CompanyCategoryException
{

    public int CompanyId { get; set; }

    public int CategoryId { get; set; }

    public System.DateTime CreatedOn { get; set; }



    public virtual SupportCategory SupportCategory { get; set; }

}


public partial class CompanyContract
{

    public CompanyContract()
    {

        this.Tickets = new HashSet<Ticket>();

    }


    public int CompanyContractId { get; set; }

    public int CompanyId { get; set; }

    public int ContractId { get; set; }

    public int ContractNumber { get; set; }

    public System.DateTime StartDate { get; set; }

    public System.DateTime EndDate { get; set; }

    public decimal Price { get; set; }

    public System.DateTime CreatedOn { get; set; }

    public string CreatedBy { get; set; }

    public System.DateTime ModifiedOn { get; set; }

    public string ModifiedBy { get; set; }



    public virtual ICollection<Ticket> Tickets { get; set; }

}


public partial class CompanyProduct
{

    public int CompanyId { get; set; }

    public int SupplierId { get; set; }

    public int SupplierProductId { get; set; }

    public string SerialNumber { get; set; }

    public string PartNumber { get; set; }

    public string Location { get; set; }

    public string FirmwareVersion { get; set; }

    public Nullable<System.DateTime> PurchaseDate { get; set; }

    public string IPAddress { get; set; }

    public string Power { get; set; }

    public string Note { get; set; }

    public string Equipment { get; set; }

    public string Credentials { get; set; }

    public Nullable<decimal> SalePrice { get; set; }

    public Nullable<decimal> PurchasePrice { get; set; }

    public Nullable<short> GuaranteeMonths { get; set; }

    public System.DateTime CreatedOn { get; set; }

    public string CreatedBy { get; set; }

    public System.DateTime ModifiedOn { get; set; }

    public string ModifiedBy { get; set; }

}


public partial class Config
{

    public int Id { get; set; }

    public string Type { get; set; }

    public string Name { get; set; }

    public string Value { get; set; }

}


public partial class ContractTemplate
{

    public int ContractTemplateId { get; set; }

    public string TemplateName { get; set; }

    public string Description { get; set; }

    public Nullable<int> NoOfTickets { get; set; }

    public Nullable<int> ResponseWithInHours { get; set; }

    public Nullable<int> SolutionWithInHours { get; set; }

    public Nullable<int> Hours { get; set; }

    public bool IsEnable { get; set; }

    public System.DateTime CreatedOn { get; set; }

    public string CreatedBy { get; set; }

    public System.DateTime ModifiedOn { get; set; }

    public string ModifiedBy { get; set; }

}


public partial class CuteChat4_InstantMessage
{

    public int MessageId { get; set; }

    public System.DateTime MsgTime { get; set; }

    public string Sender { get; set; }

    public string SenderId { get; set; }

    public string Target { get; set; }

    public string TargetId { get; set; }

    public int Offline { get; set; }

    public Nullable<int> DeletedBySender { get; set; }

    public Nullable<int> DeletedByTarget { get; set; }

    public string IPAddress { get; set; }

    public string Text { get; set; }

    public string Html { get; set; }

}


public partial class CuteChat4_Lobby
{

    public int LobbyId { get; set; }

    public string Title { get; set; }

    public string Topic { get; set; }

    public string Announcement { get; set; }

    public bool Locked { get; set; }

    public bool AllowAnonymous { get; set; }

    public string Password { get; set; }

    public string Description { get; set; }

    public string Integration { get; set; }

    public string ManagerList { get; set; }

    public int MaxOnlineCount { get; set; }

    public int MaxIdleMinute { get; set; }

    public int AutoAwayMinute { get; set; }

    public int HistoryCount { get; set; }

    public int HistoryDay { get; set; }

    public int SortIndex { get; set; }

}


public partial class CuteChat4_LogEvent
{

    public int EventId { get; set; }

    public System.DateTime EvtTime { get; set; }

    public string Category { get; set; }

    public string Message { get; set; }

    public string Portal { get; set; }

    public string Place { get; set; }

    public string UserName { get; set; }

    public string UserId { get; set; }

}


public partial class CuteChat4_LogMessage
{

    public int MessageId { get; set; }

    public System.DateTime MsgTime { get; set; }

    public string Location { get; set; }

    public string Place { get; set; }

    public string Sender { get; set; }

    public string SenderId { get; set; }

    public string Target { get; set; }

    public string TargetId { get; set; }

    public int Whisper { get; set; }

    public string IPAddress { get; set; }

    public string Text { get; set; }

    public string Html { get; set; }

}


public partial class CuteChat4_Portal
{

    public string PortalName { get; set; }

    public string Properties { get; set; }

}


public partial class CuteChat4_Rule
{

    public int RuleId { get; set; }

    public string Category { get; set; }

    public int SortIndex { get; set; }

    public string RuleMode { get; set; }

    public string Expression { get; set; }

    public bool Disabled { get; set; }

}


public partial class CuteChat4_Settings
{

    public string SettingName { get; set; }

    public string SettingData { get; set; }

}


public partial class CuteChat4_SupportAgent
{

    public int DepartmentId { get; set; }

    public string AgentUserId { get; set; }



    public virtual CuteChat4_SupportDepartment CuteChat4_SupportDepartment { get; set; }

}


public partial class CuteChat4_SupportCustomer
{

    public string CustomerId { get; set; }

    public string CustomerData { get; set; }

}


public partial class CuteChat4_SupportDepartment
{

    public CuteChat4_SupportDepartment()
    {

        this.CuteChat4_SupportAgent = new HashSet<CuteChat4_SupportAgent>();

    }


    public int DepartmentId { get; set; }

    public string DepartmentName { get; set; }



    public virtual ICollection<CuteChat4_SupportAgent> CuteChat4_SupportAgent { get; set; }

}


public partial class CuteChat4_SupportFeedback
{

    public int FeedbackId { get; set; }

    public System.DateTime FbTime { get; set; }

    public string CustomerId { get; set; }

    public string DisplayName { get; set; }

    public string Name { get; set; }

    public string Email { get; set; }

    public string Title { get; set; }

    public string Content { get; set; }

    public string Comment { get; set; }

    public string CommentBy { get; set; }

}


public partial class CuteChat4_SupportMessage
{

    public int MessageId { get; set; }

    public System.DateTime MsgTime { get; set; }

    public int SessionId { get; set; }

    public string MsgType { get; set; }

    public string Sender { get; set; }

    public string SenderId { get; set; }

    public string Target { get; set; }

    public string TargetId { get; set; }

    public string Text { get; set; }

    public string Html { get; set; }

}


public partial class CuteChat4_SupportSession
{

    public int SessionId { get; set; }

    public System.DateTime BeginTime { get; set; }

    public int DepartmentId { get; set; }

    public string AgentUserId { get; set; }

    public string CustomerId { get; set; }

    public string DisplayName { get; set; }

    public System.DateTime ActiveTime { get; set; }

    public string Email { get; set; }

    public string IPAddress { get; set; }

    public string Culture { get; set; }

    public string Platform { get; set; }

    public string Browser { get; set; }

    public int AgentRating { get; set; }

    public string SessionData { get; set; }

    public string Url { get; set; }

    public string Referrer { get; set; }

}


public partial class CuteChat4_User
{

    public string UserId { get; set; }

    public string DisplayName { get; set; }

    public string Description { get; set; }

    public string BuildinIgnores { get; set; }

    public string BuildinContacts { get; set; }

    public string ServerProperties { get; set; }

    public string PublicProperties { get; set; }

    public string PrivateProperties { get; set; }

}


public partial class EmailBlackList
{

    public int Id { get; set; }

    public string MailAddress { get; set; }

    public bool DeleteOnRead { get; set; }

}


public partial class EmailInbox
{

    public int Id { get; set; }

    public Nullable<bool> Processed { get; set; }

    public Nullable<int> UserId { get; set; }

    public string MessageId { get; set; }

    public Nullable<System.DateTime> Date { get; set; }

    public string FromAddress { get; set; }

    public string Subject { get; set; }

    public string Body { get; set; }

    public Nullable<short> Attachments { get; set; }

    public string FileName { get; set; }

    public string LinkedToTicketId { get; set; }

}


public partial class EmailQueue
{

    public int id { get; set; }

    public string From { get; set; }

    public string To { get; set; }

    public string FromName { get; set; }

    public string ToName { get; set; }

    public string CC { get; set; }

    public string BCC { get; set; }

    public string Subject { get; set; }

    public string Body { get; set; }

    public Nullable<System.DateTime> FailureDate { get; set; }

    public string FailureReason { get; set; }

    public Nullable<System.DateTime> CreatedOn { get; set; }

    public Nullable<System.DateTime> ExpiredOn { get; set; }

    public Nullable<int> NoOfRetry { get; set; }

}


public partial class EmailTemplate
{

    public int EmailTemplateId { get; set; }

    public string EmailType { get; set; }

    public string Key { get; set; }

    public Nullable<int> LanguageId { get; set; }

    public string Subject { get; set; }

    public string Body { get; set; }

    public Nullable<bool> IsHtml { get; set; }

    public Nullable<bool> IsEnable { get; set; }

    public string PredefinedTags { get; set; }

    public Nullable<System.DateTime> ModifiedOn { get; set; }

    public string ModifiedBy { get; set; }

    public string MailTo { get; set; }

    public string MailCC { get; set; }



    public virtual Language Language { get; set; }

}


public partial class Event
{

    public int EventId { get; set; }

    public System.Guid TicketId { get; set; }

    public System.DateTime CreatedOn { get; set; }

    public string EventDescription { get; set; }

}


public partial class KBArticle
{

    public int ArticleId { get; set; }

    public int KBCategoryId { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public Nullable<int> AuthorId { get; set; }

    public System.DateTime CreatedOn { get; set; }

    public string CreatedBy { get; set; }

    public System.DateTime ModifiedOn { get; set; }

    public string ModifiedBy { get; set; }



    public virtual User User { get; set; }

}


public partial class KBCategory
{

    public int KBCategoryId { get; set; }

    public string CategoryName { get; set; }

    public bool IsEnable { get; set; }

    public int ParentId { get; set; }

    public System.DateTime CreatedOn { get; set; }

    public string CreatedBy { get; set; }

    public System.DateTime ModifiedOn { get; set; }

    public string ModifiedBy { get; set; }

}


public partial class Language
{

    public Language()
    {

        this.EmailTemplates = new HashSet<EmailTemplate>();

    }


    public int Id { get; set; }

    public string Description { get; set; }



    public virtual ICollection<EmailTemplate> EmailTemplates { get; set; }

}


public partial class OperatorPermission
{

    public int OperatorId { get; set; }

    public int PermissionId { get; set; }

    public System.DateTime CreatedOn { get; set; }



    public virtual Permission Permission { get; set; }

    public virtual User User { get; set; }

}


public partial class Permission
{

    public Permission()
    {

        this.OperatorPermissions = new HashSet<OperatorPermission>();

        this.SupportTeamPermissions = new HashSet<SupportTeamPermission>();

    }


    public int PermissionId { get; set; }

    public string Type { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }



    public virtual ICollection<OperatorPermission> OperatorPermissions { get; set; }

    public virtual ICollection<SupportTeamPermission> SupportTeamPermissions { get; set; }

}


public partial class PhoneCall
{

    public int Id { get; set; }

    public System.DateTime Date { get; set; }

    public string Phone { get; set; }

    public Nullable<int> UserId { get; set; }

    public string Comment { get; set; }

    public Nullable<int> TicketId { get; set; }

    public Nullable<int> CallTime { get; set; }

    public Nullable<bool> Processed { get; set; }



    public virtual User User { get; set; }

}


public partial class Role
{

    public Role()
    {

        this.Users = new HashSet<User>();

    }


    public int RoleId { get; set; }

    public string RoleName { get; set; }



    public virtual ICollection<User> Users { get; set; }

}


public partial class Supplier
{

    public int Id { get; set; }

    public string Description { get; set; }

    public string Address { get; set; }

    public Nullable<int> CAP { get; set; }

    public string City { get; set; }

    public string Contact { get; set; }

    public string ContactName1 { get; set; }

    public string ContactName2 { get; set; }

    public string VAT { get; set; }

    public string Mail1 { get; set; }

    public string Mail2 { get; set; }

    public string PEC { get; set; }

    public string Skype { get; set; }

    public string Site1 { get; set; }

    public string Site2 { get; set; }

    public Nullable<short> Discount1 { get; set; }

    public Nullable<short> Discount2 { get; set; }

    public System.DateTime CreatedOn { get; set; }

    public string CreatedBy { get; set; }

    public System.DateTime ModifiedOn { get; set; }

    public string ModifiedBy { get; set; }

}


public partial class SupplierProduct
{

    public int Id { get; set; }

    public Nullable<int> SupplierId { get; set; }

    public Nullable<int> TypeId { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public string Note { get; set; }

    public Nullable<decimal> SalePrice1 { get; set; }

    public string SalePrice1Description { get; set; }

    public Nullable<decimal> SalePrice2 { get; set; }

    public string SalePrice2Description { get; set; }

    public Nullable<decimal> PurchasePrice { get; set; }

    public System.DateTime CreatedOn { get; set; }

    public string CreatedBy { get; set; }

    public System.DateTime ModifiedOn { get; set; }

    public string ModifiedBy { get; set; }

}


public partial class SupplierProductsType
{

    public int Id { get; set; }

    public string Description { get; set; }

    public Nullable<bool> IsHardware { get; set; }

    public System.DateTime CreatedOn { get; set; }

    public string CreatedBy { get; set; }

    public System.DateTime ModifiedOn { get; set; }

    public string ModifiedBy { get; set; }

}


public partial class SupportCategory
{

    public SupportCategory()
    {

        this.AutoAssigns = new HashSet<AutoAssign>();

        this.CompanyCategoryExceptions = new HashSet<CompanyCategoryException>();

        this.Tickets = new HashSet<Ticket>();

    }


    public int CategoryId { get; set; }

    public string CategoryName { get; set; }

    public bool IsEnable { get; set; }

    public Nullable<int> ParentId { get; set; }

    public bool DefaultForNewTicket { get; set; }

    public System.DateTime CreatedOn { get; set; }

    public string CreatedBy { get; set; }

    public System.DateTime ModifiedOn { get; set; }

    public string ModifiedBy { get; set; }



    public virtual ICollection<AutoAssign> AutoAssigns { get; set; }

    public virtual ICollection<CompanyCategoryException> CompanyCategoryExceptions { get; set; }

    public virtual ICollection<Ticket> Tickets { get; set; }

}


public partial class SupportTeam
{

    public SupportTeam()
    {

        this.AutoAssigns = new HashSet<AutoAssign>();

        this.SupportTeamMembers = new HashSet<SupportTeamMember>();

        this.SupportTeamPermissions = new HashSet<SupportTeamPermission>();

    }


    public int TeamId { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public bool IsEnable { get; set; }

    public System.DateTime CreatedOn { get; set; }

    public string CreatedBy { get; set; }

    public System.DateTime ModifiedOn { get; set; }

    public string ModifiedBy { get; set; }



    public virtual ICollection<AutoAssign> AutoAssigns { get; set; }

    public virtual ICollection<SupportTeamMember> SupportTeamMembers { get; set; }

    public virtual ICollection<SupportTeamPermission> SupportTeamPermissions { get; set; }

}


public partial class SupportTeamMember
{

    public int TeamId { get; set; }

    public int UserId { get; set; }

    public System.DateTime CreatedOn { get; set; }



    public virtual SupportTeam SupportTeam { get; set; }

    public virtual User User { get; set; }

}


public partial class SupportTeamPermission
{

    public int PermissionId { get; set; }

    public int TeamId { get; set; }

    public System.DateTime CreatedOn { get; set; }



    public virtual Permission Permission { get; set; }

    public virtual SupportTeam SupportTeam { get; set; }

}


public partial class Ticket
{

    public int TicketId { get; set; }

    public System.Guid TicketGuid { get; set; }

    public string TicketViewId { get; set; }

    public Nullable<int> SourceId { get; set; }

    public string Title { get; set; }

    public string ProblemDescription { get; set; }

    public int CompanyId { get; set; }

    public int ContractId { get; set; }

    public int CompanyUserId { get; set; }

    public int CategoryId { get; set; }

    public int CurrentStatus { get; set; }

    public int CustomerPriority { get; set; }

    public int OperatorPriority { get; set; }

    public Nullable<int> AssignToSupportTeam { get; set; }

    public Nullable<int> AssignToOperator { get; set; }

    public Nullable<System.DateTime> ResponseDeadline { get; set; }

    public Nullable<System.DateTime> ResponseDate { get; set; }

    public Nullable<System.DateTime> SolutionDeadline { get; set; }

    public Nullable<System.DateTime> SolutionDate { get; set; }

    public bool IsInGuarantee { get; set; }

    public Nullable<System.DateTime> CreatedOn { get; set; }

    public Nullable<int> CreatedByOpt { get; set; }

    public Nullable<int> CreatedByUser { get; set; }

    public Nullable<System.DateTime> ClosedOn { get; set; }

    public Nullable<int> ClosedBy { get; set; }



    public virtual CompanyContract CompanyContract { get; set; }

    public virtual TicketPriority TicketPriority { get; set; }

    public virtual TicketPriority TicketPriority1 { get; set; }

    public virtual TicketStatu TicketStatu { get; set; }

    public virtual SupportCategory SupportCategory { get; set; }

    public virtual Company Company { get; set; }

}


public partial class TicketActivity
{

    public int Id { get; set; }

    public int TicketId { get; set; }

    public string Description { get; set; }

    public string Note { get; set; }

    public System.DateTime FromDate { get; set; }

    public System.DateTime ToDate { get; set; }

    public bool SubtractFromContract { get; set; }

    public System.DateTime CreatedOn { get; set; }

    public string CreatedBy { get; set; }

    public System.DateTime ModifiedOn { get; set; }

    public string ModifiedBy { get; set; }

}


public partial class TicketPriority
{

    public TicketPriority()
    {

        this.Tickets = new HashSet<Ticket>();

        this.Tickets1 = new HashSet<Ticket>();

    }


    public int TicketPriorityId { get; set; }

    public string Description { get; set; }

    public int Type { get; set; }

    public bool IsEnable { get; set; }

    public bool DefaultForNewTicket { get; set; }

    public string CreatedBy { get; set; }

    public Nullable<System.DateTime> CreatedOn { get; set; }

    public Nullable<System.DateTime> ModifiedOn { get; set; }

    public string ModifiedBy { get; set; }

    public int OrderByNo { get; set; }



    public virtual ICollection<Ticket> Tickets { get; set; }

    public virtual ICollection<Ticket> Tickets1 { get; set; }

}


public partial class TicketsSource
{

    public int Id { get; set; }

    public string Description { get; set; }

    public bool DefaultForMail { get; set; }

    public bool DefaultForTicket { get; set; }

}


public partial class TicketStatu
{

    public TicketStatu()
    {

        this.Tickets = new HashSet<Ticket>();

    }


    public int TicketStatusId { get; set; }

    public string StatusName { get; set; }

    public bool IsEnable { get; set; }

    public bool DefaultForNewTicket { get; set; }

    public bool IsClosedStatus { get; set; }

    public string IconColor { get; set; }

    public System.DateTime CreatedOn { get; set; }

    public string CreatedBy { get; set; }

    public System.DateTime ModifiedOn { get; set; }

    public string ModifiedBy { get; set; }

    public int OrderByNo { get; set; }



    public virtual ICollection<Ticket> Tickets { get; set; }

}


public partial class User
{

    public User()
    {

        this.AutoAssigns = new HashSet<AutoAssign>();

        this.KBArticles = new HashSet<KBArticle>();

        this.OperatorPermissions = new HashSet<OperatorPermission>();

        this.SupportTeamMembers = new HashSet<SupportTeamMember>();

        this.PhoneCalls = new HashSet<PhoneCall>();

    }


    public int UserId { get; set; }

    public int RoleId { get; set; }

    public Nullable<int> LanguageId { get; set; }

    public string Name { get; set; }

    public string Email { get; set; }

    public string Password { get; set; }

    public string AccessPassword { get; set; }

    public string Contact { get; set; }

    public string ContactDescription { get; set; }

    public string Contact1 { get; set; }

    public string Contact1Description { get; set; }

    public string Skype { get; set; }

    public string RoleDescription { get; set; }

    public bool IsEnable { get; set; }

    public string VerificationToken { get; set; }

    public Nullable<System.DateTime> VerificationTokenExpirationDate { get; set; }

    public Nullable<int> CompanyId { get; set; }

    public System.DateTime CreatedOn { get; set; }

    public string CreatedBy { get; set; }

    public System.DateTime ModifiedOn { get; set; }

    public string ModifiedBy { get; set; }



    public virtual ICollection<AutoAssign> AutoAssigns { get; set; }

    public virtual ICollection<KBArticle> KBArticles { get; set; }

    public virtual ICollection<OperatorPermission> OperatorPermissions { get; set; }

    public virtual Role Role { get; set; }

    public virtual ICollection<SupportTeamMember> SupportTeamMembers { get; set; }

    public virtual ICollection<PhoneCall> PhoneCalls { get; set; }

    public virtual Company Company { get; set; }

}


public partial class vw_AutoAssign
{

    public int Id { get; set; }

    public Nullable<int> CategoryId { get; set; }

    public Nullable<int> CompanyId { get; set; }

    public Nullable<int> OperatorId { get; set; }

    public Nullable<int> SupportTeamId { get; set; }

    public Nullable<System.DateTime> CreatedOn { get; set; }

    public string CreatedBy { get; set; }

    public Nullable<System.DateTime> ModifiedOn { get; set; }

    public string ModifiedBy { get; set; }

    public string CompanyName { get; set; }

    public string CategoryName { get; set; }

    public string TeamName { get; set; }

    public string Name { get; set; }

}


public partial class vw_Comments
{

    public int CommentId { get; set; }

    public System.Guid TicketId { get; set; }

    public bool IsPrivate { get; set; }

    public string CommentText { get; set; }

    public Nullable<int> CreatedOpt_Id { get; set; }

    public Nullable<int> CreatedUser_Id { get; set; }

    public System.DateTime CreatedOn { get; set; }

    public string OperatorName { get; set; }

    public string CustomerName { get; set; }

}


public partial class vw_CompanyCategoryException
{

    public int CompanyId { get; set; }

    public string CompanyName { get; set; }

    public int CategoryId { get; set; }

    public string CategoryName { get; set; }

}


public partial class vw_CompanyContract
{

    public int CompanyContractId { get; set; }

    public int CompanyId { get; set; }

    public string CompanyName { get; set; }

    public Nullable<int> CategoryId { get; set; }

    public string CategoryName { get; set; }

    public int ContractTemplateId { get; set; }

    public string TemplateName { get; set; }

    public int ContractNumber { get; set; }

    public string ModifiedBy { get; set; }

    public System.DateTime ModifiedOn { get; set; }

    public string CreatedBy { get; set; }

    public System.DateTime CreatedOn { get; set; }

    public System.DateTime EndDate { get; set; }

    public System.DateTime StartDate { get; set; }

    public Nullable<int> TicketsLeft { get; set; }

    public Nullable<int> ResponseWithInHours { get; set; }

    public Nullable<int> SolutionWithInHours { get; set; }

    public Nullable<int> NoOfTickets { get; set; }

    public bool IsEnable { get; set; }

    public decimal Price { get; set; }

    public Nullable<int> Hours { get; set; }

    public Nullable<int> ParentId { get; set; }

    public bool ShareParentContract { get; set; }

}


public partial class vw_CompanyUser
{

    public int RoleId { get; set; }

    public string Name { get; set; }

    public string Email { get; set; }

    public string Password { get; set; }

    public string Contact { get; set; }

    public bool IsEnable { get; set; }

    public System.DateTime CreatedOn { get; set; }

    public string CreatedBy { get; set; }

    public System.DateTime ModifiedOn { get; set; }

    public string ModifiedBy { get; set; }

    public string RoleName { get; set; }

    public Nullable<int> CompanyId { get; set; }

    public int UserId { get; set; }

    public string CompanyName { get; set; }

}


public partial class vw_Events
{

    public int EventId { get; set; }

    public System.DateTime CreatedOn { get; set; }

    public string EventDescription { get; set; }

    public string TicketViewId { get; set; }

    public System.Guid TicketGuid { get; set; }

}


public partial class vw_KBArticle
{

    public int ArticleId { get; set; }

    public int KBCategoryId { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public System.DateTime CreatedOn { get; set; }

    public string CreatedBy { get; set; }

    public System.DateTime ModifiedOn { get; set; }

    public string ModifiedBy { get; set; }

    public string CategoryName { get; set; }

    public Nullable<int> AuthorId { get; set; }

}


public partial class vw_KBCategory
{

    public int KBCategoryId { get; set; }

    public string CategoryName { get; set; }

    public bool IsEnable { get; set; }

    public int ParentId { get; set; }

    public System.DateTime CreatedOn { get; set; }

    public System.DateTime ModifiedOn { get; set; }

    public string CreatedBy { get; set; }

    public string ModifiedBy { get; set; }

    public string ParentCategoryName { get; set; }

}


public partial class vw_SupportCategory
{

    public int CategoryId { get; set; }

    public string CategoryName { get; set; }

    public bool IsEnable { get; set; }

    public Nullable<int> ParentId { get; set; }

    public System.DateTime CreatedOn { get; set; }

    public string CreatedBy { get; set; }

    public System.DateTime ModifiedOn { get; set; }

    public string ModifiedBy { get; set; }

    public string ParentCategoryName { get; set; }

    public bool DefaultForNewTicket { get; set; }

}


public partial class vw_SupportTicket
{

    public int TicketId { get; set; }

    public System.Guid TicketGuid { get; set; }

    public string TicketViewId { get; set; }

    public string Title { get; set; }

    public int CompanyId { get; set; }

    public string CompanyName { get; set; }

    public int ContractId { get; set; }

    public string ContractName { get; set; }

    public string CategoryName { get; set; }

    public int CategoryId { get; set; }

    public string ProblemDescription { get; set; }

    public string AssignToName { get; set; }

    public int CurrentStatusId { get; set; }

    public string StatusName { get; set; }

    public int CustomerPriorityId { get; set; }

    public int OperatorPriorityId { get; set; }

    public Nullable<int> AssignToOperator { get; set; }

    public Nullable<int> AssignToSupportTeam { get; set; }

    public string StatusColor { get; set; }

    public string CustomerPriority { get; set; }

    public string OperatorPriority { get; set; }

    public Nullable<int> ResponseWithInHours { get; set; }

    public Nullable<int> SolutionWithInHours { get; set; }

    public int CompanyUserId { get; set; }

    public string CompanyUserName { get; set; }

    public Nullable<System.DateTime> CreatedOn { get; set; }

    public Nullable<System.DateTime> ClosedOn { get; set; }

    public Nullable<System.DateTime> ResponseDeadline { get; set; }

    public Nullable<System.DateTime> SolutionDeadline { get; set; }

    public Nullable<int> CreatedByOpt { get; set; }

    public string CreatedByOperatorName { get; set; }

    public Nullable<int> CreatedByUser { get; set; }

    public string CreatedByUserName { get; set; }

    public Nullable<int> ClosedBy { get; set; }

    public Nullable<System.DateTime> ResponseDate { get; set; }

    public Nullable<System.DateTime> SolutionDate { get; set; }

    public string ResponseStatus { get; set; }

    public string SolutionStatus { get; set; }

    public string SolutionInPercentage { get; set; }

    public string Email { get; set; }

    public Nullable<int> PhoneCall { get; set; }

    public Nullable<int> Activity { get; set; }

}


public partial class vw_User
{

    public int RoleId { get; set; }

    public string Name { get; set; }

    public string Email { get; set; }

    public string Password { get; set; }

    public string Contact { get; set; }

    public bool IsEnable { get; set; }

    public System.DateTime CreatedOn { get; set; }

    public string CreatedBy { get; set; }

    public System.DateTime ModifiedOn { get; set; }

    public string ModifiedBy { get; set; }

    public string RoleName { get; set; }

    public Nullable<int> CompanyId { get; set; }

    public int UserId { get; set; }

}


public partial class sp_GetCategoryList_Result
{

    public string CategoryName { get; set; }

    public Nullable<int> KBCategoryId { get; set; }

}


public partial class sp_GetSupportCategoryList_Result
{

    public string CategoryName { get; set; }

    public Nullable<int> CategoryId { get; set; }

}

