//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelpDeskEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupportCategory
    {
        public SupportCategory()
        {
            this.AutoAssigns = new HashSet<AutoAssign>();
            this.CompanyCategoryExceptions = new HashSet<CompanyCategoryException>();
            this.Tickets = new HashSet<Ticket>();
        }
    
        public int CategoryId { get; set; }
        public string CategoryName { get; set; }
        public bool IsEnable { get; set; }
        public Nullable<int> ParentId { get; set; }
        public bool DefaultForNewTicket { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime ModifiedOn { get; set; }
        public string ModifiedBy { get; set; }
    
        public virtual ICollection<AutoAssign> AutoAssigns { get; set; }
        public virtual ICollection<CompanyCategoryException> CompanyCategoryExceptions { get; set; }
        public virtual ICollection<Ticket> Tickets { get; set; }
    }
}
