//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelpDeskEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supplier
    {
        public int Id { get; set; }
        public string Description { get; set; }
        public string Address { get; set; }
        public Nullable<int> CAP { get; set; }
        public string City { get; set; }
        public string Contact { get; set; }
        public string ContactName1 { get; set; }
        public string ContactName2 { get; set; }
        public string VAT { get; set; }
        public string Mail1 { get; set; }
        public string Mail2 { get; set; }
        public string PEC { get; set; }
        public string Skype { get; set; }
        public string Site1 { get; set; }
        public string Site2 { get; set; }
        public Nullable<short> Discount1 { get; set; }
        public Nullable<short> Discount2 { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime ModifiedOn { get; set; }
        public string ModifiedBy { get; set; }
    }
}
