//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelpDeskEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupportTeam
    {
        public SupportTeam()
        {
            this.AutoAssigns = new HashSet<AutoAssign>();
            this.SupportTeamMembers = new HashSet<SupportTeamMember>();
            this.SupportTeamPermissions = new HashSet<SupportTeamPermission>();
        }
    
        public int TeamId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public bool IsEnable { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime ModifiedOn { get; set; }
        public string ModifiedBy { get; set; }
    
        public virtual ICollection<AutoAssign> AutoAssigns { get; set; }
        public virtual ICollection<SupportTeamMember> SupportTeamMembers { get; set; }
        public virtual ICollection<SupportTeamPermission> SupportTeamPermissions { get; set; }
    }
}
