//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelpDeskEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketStatu
    {
        public TicketStatu()
        {
            this.Tickets = new HashSet<Ticket>();
        }
    
        public int TicketStatusId { get; set; }
        public string StatusName { get; set; }
        public bool IsEnable { get; set; }
        public bool DefaultForNewTicket { get; set; }
        public bool IsClosedStatus { get; set; }
        public string IconColor { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime ModifiedOn { get; set; }
        public string ModifiedBy { get; set; }
        public int OrderByNo { get; set; }
    
        public virtual ICollection<Ticket> Tickets { get; set; }
    }
}
