//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelpDeskEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public int TicketId { get; set; }
        public System.Guid TicketGuid { get; set; }
        public string TicketViewId { get; set; }
        public Nullable<int> SourceId { get; set; }
        public string Title { get; set; }
        public string ProblemDescription { get; set; }
        public int CompanyId { get; set; }
        public int ContractId { get; set; }
        public int CompanyUserId { get; set; }
        public int CategoryId { get; set; }
        public int CurrentStatus { get; set; }
        public int CustomerPriority { get; set; }
        public int OperatorPriority { get; set; }
        public Nullable<int> AssignToSupportTeam { get; set; }
        public Nullable<int> AssignToOperator { get; set; }
        public Nullable<System.DateTime> ResponseDeadline { get; set; }
        public Nullable<System.DateTime> ResponseDate { get; set; }
        public Nullable<System.DateTime> SolutionDeadline { get; set; }
        public Nullable<System.DateTime> SolutionDate { get; set; }
        public bool IsInGuarantee { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> CreatedByOpt { get; set; }
        public Nullable<int> CreatedByUser { get; set; }
        public Nullable<System.DateTime> ClosedOn { get; set; }
        public Nullable<int> ClosedBy { get; set; }
    
        public virtual CompanyContract CompanyContract { get; set; }
        public virtual TicketPriority TicketPriority { get; set; }
        public virtual TicketPriority TicketPriority1 { get; set; }
        public virtual TicketStatu TicketStatu { get; set; }
        public virtual SupportCategory SupportCategory { get; set; }
        public virtual Company Company { get; set; }
    }
}
