//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelpDeskEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketsSource
    {
        public int Id { get; set; }
        public string Description { get; set; }
        public bool DefaultForMail { get; set; }
        public bool DefaultForTicket { get; set; }
    }
}
