//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelpDeskEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.AutoAssigns = new HashSet<AutoAssign>();
            this.KBArticles = new HashSet<KBArticle>();
            this.OperatorPermissions = new HashSet<OperatorPermission>();
            this.SupportTeamMembers = new HashSet<SupportTeamMember>();
            this.PhoneCalls = new HashSet<PhoneCall>();
        }
    
        public int UserId { get; set; }
        public int RoleId { get; set; }
        public Nullable<int> LanguageId { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string AccessPassword { get; set; }
        public string Contact { get; set; }
        public string ContactDescription { get; set; }
        public string Contact1 { get; set; }
        public string Contact1Description { get; set; }
        public string Skype { get; set; }
        public string RoleDescription { get; set; }
        public bool IsEnable { get; set; }
        public string VerificationToken { get; set; }
        public Nullable<System.DateTime> VerificationTokenExpirationDate { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime ModifiedOn { get; set; }
        public string ModifiedBy { get; set; }
    
        public virtual ICollection<AutoAssign> AutoAssigns { get; set; }
        public virtual ICollection<KBArticle> KBArticles { get; set; }
        public virtual ICollection<OperatorPermission> OperatorPermissions { get; set; }
        public virtual Role Role { get; set; }
        public virtual ICollection<SupportTeamMember> SupportTeamMembers { get; set; }
        public virtual ICollection<PhoneCall> PhoneCalls { get; set; }
        public virtual Company Company { get; set; }
    }
}
