//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelpDeskEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_CompanyContract
    {
        public int CompanyContractId { get; set; }
        public int CompanyId { get; set; }
        public string CompanyName { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public string CategoryName { get; set; }
        public int ContractTemplateId { get; set; }
        public string TemplateName { get; set; }
        public int ContractNumber { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedOn { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.DateTime EndDate { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<int> TicketsLeft { get; set; }
        public Nullable<int> ResponseWithInHours { get; set; }
        public Nullable<int> SolutionWithInHours { get; set; }
        public Nullable<int> NoOfTickets { get; set; }
        public bool IsEnable { get; set; }
        public decimal Price { get; set; }
        public Nullable<int> Hours { get; set; }
        public Nullable<int> ParentId { get; set; }
        public bool ShareParentContract { get; set; }
    }
}
