//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelpDeskEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Comments
    {
        public int CommentId { get; set; }
        public System.Guid TicketId { get; set; }
        public bool IsPrivate { get; set; }
        public string CommentText { get; set; }
        public Nullable<int> CreatedOpt_Id { get; set; }
        public Nullable<int> CreatedUser_Id { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string OperatorName { get; set; }
        public string CustomerName { get; set; }
    }
}
