//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelpDeskEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Events
    {
        public int EventId { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string EventDescription { get; set; }
        public string TicketViewId { get; set; }
        public System.Guid TicketGuid { get; set; }
    }
}
