//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelpDeskEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_SupportTicket
    {
        public int TicketId { get; set; }
        public System.Guid TicketGuid { get; set; }
        public string TicketViewId { get; set; }
        public string Title { get; set; }
        public int CompanyId { get; set; }
        public string CompanyName { get; set; }
        public int ContractId { get; set; }
        public string ContractName { get; set; }
        public string CategoryName { get; set; }
        public int CategoryId { get; set; }
        public string ProblemDescription { get; set; }
        public string AssignToName { get; set; }
        public int CurrentStatusId { get; set; }
        public string StatusName { get; set; }
        public int CustomerPriorityId { get; set; }
        public int OperatorPriorityId { get; set; }
        public Nullable<int> AssignToOperator { get; set; }
        public Nullable<int> AssignToSupportTeam { get; set; }
        public string StatusColor { get; set; }
        public string CustomerPriority { get; set; }
        public string OperatorPriority { get; set; }
        public Nullable<int> ResponseWithInHours { get; set; }
        public Nullable<int> SolutionWithInHours { get; set; }
        public int CompanyUserId { get; set; }
        public string CompanyUserName { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> ClosedOn { get; set; }
        public Nullable<System.DateTime> ResponseDeadline { get; set; }
        public Nullable<System.DateTime> SolutionDeadline { get; set; }
        public Nullable<int> CreatedByOpt { get; set; }
        public string CreatedByOperatorName { get; set; }
        public Nullable<int> CreatedByUser { get; set; }
        public string CreatedByUserName { get; set; }
        public Nullable<int> ClosedBy { get; set; }
        public Nullable<System.DateTime> ResponseDate { get; set; }
        public Nullable<System.DateTime> SolutionDate { get; set; }
        public string ResponseStatus { get; set; }
        public string SolutionStatus { get; set; }
        public string SolutionInPercentage { get; set; }
        public string Email { get; set; }
        public Nullable<int> PhoneCall { get; set; }
        public Nullable<int> Activity { get; set; }
    }
}
