//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelpDeskEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_SupportTickets
    {
        public int TicketId { get; set; }
        public string Title { get; set; }
        public int CompanyId { get; set; }
        public string CompanyName { get; set; }
        public int ContractId { get; set; }
        public string ContractName { get; set; }
        public string CategoryName { get; set; }
        public int CategoryId { get; set; }
        public string ProblemDescription { get; set; }
        public string Name { get; set; }
        public int CurrentStatusId { get; set; }
        public string StatusName { get; set; }
        public int CustomerPriorityId { get; set; }
        public int OperatorPriorityId { get; set; }
        public string OperatorPriorityName { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> AssignTo { get; set; }
        public string StatusColor { get; set; }
    }
}
